#!/usr/bin/env python3
"""Generate ros2_ws/src/dyx3_rpp/include/dyx3_rpp/rpp_param_table.inc from docs/tuning/parameter_registry.md.

The registry (name, type, prototype default, PROPOSED class) is the single source; the generated table
is committed so the C++ build needs no Python. `--check` fails if the committed file is stale.

Validation bounds are STRUCTURAL (finite; non-negative; strictly positive where the value is a divisor;
a fraction in [0, 1]) and are NOT tuning values. Anything beyond that would be an invented number.
"""
import argparse
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REGISTRY = os.path.join(ROOT, "docs/tuning/parameter_registry.md")
OUT = os.path.join(ROOT, "ros2_ws/src/dyx3_rpp/include/dyx3_rpp/rpp_param_table.inc")
OUT_IDS = os.path.join(ROOT, "ros2_ws/src/dyx3_rpp/include/dyx3_rpp/rpp_param_ids.inc")

# Structural exceptions to "float >= 0".
SIGNED = {"pose_latency_bias_s"}
FRACTION = {"closed_loop_min_travel_frac"}
POSITIVE = {  # used as divisors / periods: zero would be a division by zero or a stuck controller
    "max_linear_vel", "mission_speed", "max_linear_accel", "max_linear_decel", "speed_cmd_decel_m_s2",
    "segment_endpoint_precise_decel_m_s2", "precise_stop_decel_m_s2", "max_yaw_rate_body", "a_lat_max",
    "path_resample_spacing_m", "curvature_baseline_m", "pose_max_age_s", "rtk_fix_timeout_s", "lookahead_time",
    "min_lookahead_dist", "max_lookahead_dist",
}
ALLOWED = {
    "tracking_profile": ["auto", "segment", "smooth"],
    "precise_stop_mode": ["feedforward", "servo"],
    "point_execution_mode": ["auto", "manual"],
    "path_frame_id": None,  # any non-empty string
}
INT_MIN = {"preview_curvature_n": 1, "corner_smooth_arc_pts": 1}


def rows():
    out = []
    for line in open(REGISTRY, encoding="utf-8"):
        if not line.startswith("| `"):
            continue
        c = [x.strip() for x in line.strip().strip("|").split("|")]
        if len(c) < 7 or c[6] != "dyx3_rpp":
            continue
        name = c[0].strip("`")
        typ = c[1]
        dflt = c[2].strip("`")
        cls = c[4].strip("*")
        out.append((name, typ, dflt, cls))
    return out


def cstr(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def render():
    lines = ["// GENERATED by tools/gen_rpp_params.py from docs/tuning/parameter_registry.md. Do not edit.",
             "// {name, kind, class, default, lo, hi, nonzero, allowed}"]
    for name, typ, dflt, cls in rows():
        if cls not in ("LIVE", "IDLE_ONLY", "RESTART"):
            sys.exit(f"{name}: class {cls!r} is not LIVE/IDLE_ONLY/RESTART")
        kind = {"float": "Kind::Float", "int": "Kind::Int", "bool": "Kind::Bool", "string": "Kind::String"}[typ]
        klass = {"LIVE": "ParamClass::Live", "IDLE_ONLY": "ParamClass::IdleOnly", "RESTART": "ParamClass::Restart"}[cls]
        d = dflt
        if typ == "bool":
            d = "1" if d == "True" else "0" if d == "False" else sys.exit(f"{name}: bad bool {d}")
            dval, sdef = d, '""'
        elif typ == "string":
            sdef = cstr(d.strip('"'))
            dval = "0"
        else:
            dval = repr(float(d))
            sdef = '""'
        lo, hi, pos = "-HUGE_VAL", "HUGE_VAL", "false"
        if typ == "float":
            if name in SIGNED:
                pass
            elif name in FRACTION:
                lo, hi = "0.0", "1.0"
            else:
                lo = "0.0"
                if name in POSITIVE:
                    pos = "true"
        if typ == "int":
            lo = repr(float(INT_MIN.get(name, 0)))
        allowed = "{" + ", ".join(cstr(a) for a in ALLOWED[name]) + "}" if ALLOWED.get(name) else "{}"
        nonempty = "true" if typ == "string" else "false"
        lines.append(f"  {{{cstr(name)}, {kind}, {klass}, {dval}, {sdef}, {lo}, {hi}, {pos}, {nonempty}, {allowed}}},")
    ids = ["// GENERATED by tools/gen_rpp_params.py from docs/tuning/parameter_registry.md. Do not edit."]
    ids += [f"  {name}," for name, _t, _d, _c in rows()]
    return "\n".join(lines) + "\n", "\n".join(ids) + "\n", len(lines) - 2


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    text, ids, n = render()
    if n != 119:
        sys.exit(f"expected 119 RPP parameters in the registry, found {n}")
    if a.check:
        for path, want in ((OUT, text), (OUT_IDS, ids)):
            if not os.path.exists(path) or open(path).read() != want:
                sys.exit(f"{os.path.basename(path)} is stale: run tools/gen_rpp_params.py")
        print(f"ok: {n} parameters")
    else:
        for path, want in ((OUT, text), (OUT_IDS, ids)):
            with open(path, "w") as f:
                f.write(want)
        print(f"wrote {OUT}: {n} parameters")
