#!/usr/bin/env python3
"""Generate the C++ parameter descriptor tables from docs/tuning/parameter_registry.md.

    tools/gen_param_tables.py            # rewrite both packages' tables
    tools/gen_param_tables.py --check    # fail if a committed table is stale

The registry (name, type, prototype default, PROPOSED class) is the single source; the generated tables are
committed so the C++ build needs no Python. One table per owning package (`dyx3_rpp`: 119 carried + production additions, `dyx3_spray`: the
registry's 54 minus the rows that belong to features not ported, each excluded with a reason below).

Validation bounds are STRUCTURAL (finite; non-negative; strictly positive where the value is a divisor;
a fraction in [0, 1]) and are NOT tuning values. Anything beyond that would be an invented number.
"""
import argparse
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REGISTRY = os.path.join(ROOT, "docs/tuning/parameter_registry.md")


def out_paths(pkg):
    d = os.path.join(ROOT, "ros2_ws/src", pkg, "include", pkg)
    short = pkg.replace("dyx3_", "")
    return os.path.join(d, f"{short}_param_table.inc"), os.path.join(d, f"{short}_param_ids.inc")


# Structural exceptions to "float >= 0".
SIGNED = {"pose_latency_bias_s", "off_value"}
FRACTION = {"closed_loop_min_travel_frac"}
UNIT_RANGE = {"on_value", "off_value", "min_flow_value", "point_dwell_flow_value"}  # normalized actuator values
POSITIVE = {  # used as divisors / periods: zero would be a division by zero or a stuck controller
    "max_linear_vel", "mission_speed", "max_linear_accel", "max_linear_decel", "speed_cmd_decel_m_s2",
    "segment_endpoint_precise_decel_m_s2", "precise_stop_decel_m_s2", "max_yaw_rate_body", "a_lat_max",
    "path_resample_spacing_m", "curvature_baseline_m", "pose_max_age_s", "rtk_fix_timeout_s", "lookahead_time",
    "min_lookahead_dist", "max_lookahead_dist",
    # spray
    "rated_marking_speed_mps", "pose_timeout_s", "velocity_timeout_s", "gps_fix_timeout_s", "reassert_hz",
    "spray_watchdog_timeout_s", "manual_override_timeout_s", "rpp_timeout_s",
}
ALLOWED = {
    "tracking_profile": ["auto", "segment", "smooth"],
    "segment_command_mode": ["heading", "rate"],
    "precise_stop_mode": ["feedforward", "servo"],
    "point_execution_mode": ["auto", "manual"],
    "path_frame_id": None,  # any non-empty string
    "actuator_backend": ["mavlink_actuator", "mavlink_servo_pwm"],
}
INT_RANGE = {  # name -> (lo, hi)
    "preview_curvature_n": (1, None), "corner_smooth_arc_pts": (1, None),
    "actuator_set_index": (1, 6), "servo_instance": (1, 16), "off_pwm_us": (0, 2200), "on_pwm_us": (0, 2200),
    "spray_min_fix_type": (5, 6), "debounce_samples": (0, 100),
}

PACKAGES = {
    "dyx3_rpp": {"expect": 117, "exclude": {}},  # 119 carried + segment_command_mode - 3 spray verdict params
    "dyx3_spray": {
        "expect": 49,  # + rpp_timeout_s and C2 heading verdict parameters
        "exclude": {
            "command_service": "MAVROS service name: the valve is driven through dyx3_px4_link",
            "use_distance_aware_spray": "the legacy /spray/active path is not carried; distance-aware is the only path",
            "allow_legacy_spray_active_fallback": "the legacy /spray/active path is not carried",
            "consume_rpp_progress": "RPP-sourced boundary (G2) needs dyx3_rpp's progress output, not built",
            "progress_timeout_s": "RPP-sourced boundary (G2), not built",
            "active_timeout_s": "/spray/active heartbeat (B4) needs dyx3_rpp's spray gate, not built",
            "point_dwell_flow_value": "point mode is not ported",
            "point_arrival_max_speed_mps": "point mode is not ported",
            "point_arrival_timeout_s": "point mode is not ported",
        },
    },
}


def rows(pkg):
    out = []
    for line in open(REGISTRY, encoding="utf-8"):
        if not line.startswith("| `"):
            continue
        c = [x.strip() for x in line.strip().strip("|").split("|")]
        if len(c) < 7 or c[6] != pkg:
            continue
        name = c[0].strip("`")
        if name in PACKAGES[pkg]["exclude"]:
            continue
        typ = c[1]
        dflt = c[2].strip("`")
        cls = c[4].strip("*")
        out.append((name, typ, dflt, cls))
    return out


def cstr(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


TBD_CLASS = {"spray_enabled": "IDLE_ONLY"}  # registry says TBD - human; the conservative reading until decided


def render(pkg):
    hdr = "// GENERATED by tools/gen_param_tables.py from docs/tuning/parameter_registry.md. Do not edit."
    lines = [hdr, "// {name, kind, class, default, lo, hi, nonzero, nonempty, allowed}"]
    names = []
    for name, typ, dflt, cls in rows(pkg):
        if cls.startswith("TBD"):
            cls = TBD_CLASS.get(name, cls)
        if cls not in ("LIVE", "IDLE_ONLY", "RESTART"):
            sys.exit(f"{name}: class {cls!r} is not LIVE/IDLE_ONLY/RESTART")
        names.append(name)
        kind = {"float": "Kind::Float", "int": "Kind::Int", "bool": "Kind::Bool", "string": "Kind::String"}[typ]
        klass = {"LIVE": "ParamClass::Live", "IDLE_ONLY": "ParamClass::IdleOnly", "RESTART": "ParamClass::Restart"}[cls]
        d = dflt
        if typ == "bool":
            d = "1" if d == "True" else "0" if d == "False" else sys.exit(f"{name}: bad bool {d}")
            dval, sdef = d, '""'
        elif typ == "string":
            sdef = cstr(d.strip('"'))
            dval = "0"
        else:
            dval = repr(float(d))
            sdef = '""'
        lo, hi, pos = "-HUGE_VAL", "HUGE_VAL", "false"
        if typ == "float":
            if name in UNIT_RANGE:
                lo, hi = "-1.0", "1.0"
            elif name in SIGNED:
                pass
            elif name in FRACTION:
                lo, hi = "0.0", "1.0"
            else:
                lo = "0.0"
                if name in POSITIVE:
                    pos = "true"
        if typ == "int":
            ilo, ihi = INT_RANGE.get(name, (0, None))
            lo = repr(float(ilo))
            if ihi is not None:
                hi = repr(float(ihi))
        allowed = "{" + ", ".join(cstr(a) for a in ALLOWED[name]) + "}" if ALLOWED.get(name) else "{}"
        nonempty = "true" if typ == "string" else "false"
        lines.append(f"  {{{cstr(name)}, {kind}, {klass}, {dval}, {sdef}, {lo}, {hi}, {pos}, {nonempty}, {allowed}}},")
    ids = [hdr] + [f"  {n}," for n in names]
    return "\n".join(lines) + "\n", "\n".join(ids) + "\n", len(names)


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    for pkg, cfg in PACKAGES.items():
        text, ids, n = render(pkg)
        if n != cfg["expect"]:
            sys.exit(f"{pkg}: expected {cfg['expect']} parameters, found {n}")
        out, out_ids = out_paths(pkg)
        if a.check:
            for path, want in ((out, text), (out_ids, ids)):
                if not os.path.exists(path) or open(path).read() != want:
                    sys.exit(f"{os.path.basename(path)} is stale: run tools/gen_param_tables.py")
            print(f"ok: {pkg} {n} parameters")
        else:
            os.makedirs(os.path.dirname(out), exist_ok=True)
            for path, want in ((out, text), (out_ids, ids)):
                with open(path, "w") as f:
                    f.write(want)
            print(f"wrote {pkg}: {n} parameters")
